// <auto-generated />
using System;
using BankDataWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankDataWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    partial class DBManagerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BankDataModels.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountBalance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountHolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isActivated")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountHolderId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 11,
                            AccountBalance = 22117,
                            AccountHolderId = 1,
                            AccountName = "Checkings",
                            AccountNumber = 770065,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 12,
                            AccountBalance = 65118,
                            AccountHolderId = 1,
                            AccountName = "Deposits",
                            AccountNumber = 475083,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 13,
                            AccountBalance = 79983,
                            AccountHolderId = 1,
                            AccountName = "Savings",
                            AccountNumber = 880816,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 21,
                            AccountBalance = 96946,
                            AccountHolderId = 2,
                            AccountName = "Money Market ",
                            AccountNumber = 309277,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 22,
                            AccountBalance = 44435,
                            AccountHolderId = 2,
                            AccountName = "Money Market ",
                            AccountNumber = 751640,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 23,
                            AccountBalance = 29259,
                            AccountHolderId = 2,
                            AccountName = "Checkings",
                            AccountNumber = 733924,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 31,
                            AccountBalance = 47306,
                            AccountHolderId = 3,
                            AccountName = "Checkings",
                            AccountNumber = 897546,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 32,
                            AccountBalance = 81590,
                            AccountHolderId = 3,
                            AccountName = "Money Market ",
                            AccountNumber = 338677,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 33,
                            AccountBalance = 93060,
                            AccountHolderId = 3,
                            AccountName = "Deposits",
                            AccountNumber = 354018,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 41,
                            AccountBalance = 79693,
                            AccountHolderId = 4,
                            AccountName = "Money Market ",
                            AccountNumber = 837691,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 42,
                            AccountBalance = 56154,
                            AccountHolderId = 4,
                            AccountName = "Checkings",
                            AccountNumber = 210342,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 43,
                            AccountBalance = 60854,
                            AccountHolderId = 4,
                            AccountName = "Deposits",
                            AccountNumber = 348418,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 51,
                            AccountBalance = 43148,
                            AccountHolderId = 5,
                            AccountName = "Deposits",
                            AccountNumber = 470073,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 52,
                            AccountBalance = 96130,
                            AccountHolderId = 5,
                            AccountName = "Savings",
                            AccountNumber = 596000,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 53,
                            AccountBalance = 1924,
                            AccountHolderId = 5,
                            AccountName = "Checkings",
                            AccountNumber = 949319,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 61,
                            AccountBalance = 42475,
                            AccountHolderId = 6,
                            AccountName = "Checkings",
                            AccountNumber = 571118,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 62,
                            AccountBalance = 74905,
                            AccountHolderId = 6,
                            AccountName = "Deposits",
                            AccountNumber = 339286,
                            isActivated = true
                        },
                        new
                        {
                            AccountId = 63,
                            AccountBalance = 10159,
                            AccountHolderId = 6,
                            AccountName = "Money Market ",
                            AccountNumber = 786190,
                            isActivated = true
                        });
                });

            modelBuilder.Entity("BankDataModels.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNo")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProfilePicdBytes")
                        .HasColumnType("BLOB");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("BankDataModels.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedResource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BankDataModels.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiverAccountNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderAccountNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderName")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("SenderId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 111,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 770065,
                            SenderId = 11,
                            TransactionAmount = 4174,
                            TransactionDate = new DateTime(2024, 7, 31, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7465),
                            TransactionDescription = "Payment from 770065 to 770065"
                        },
                        new
                        {
                            TransactionId = 112,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 770065,
                            SenderId = 11,
                            TransactionAmount = 3684,
                            TransactionDate = new DateTime(2024, 7, 23, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7484),
                            TransactionDescription = "Payment from 770065 to 770065"
                        },
                        new
                        {
                            TransactionId = 113,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 770065,
                            SenderId = 11,
                            TransactionAmount = 4190,
                            TransactionDate = new DateTime(2024, 8, 8, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7486),
                            TransactionDescription = "Payment from 770065 to 770065"
                        },
                        new
                        {
                            TransactionId = 114,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 770065,
                            SenderId = 11,
                            TransactionAmount = 2040,
                            TransactionDate = new DateTime(2024, 9, 23, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7544),
                            TransactionDescription = "Payment from 770065 to 770065"
                        },
                        new
                        {
                            TransactionId = 115,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 770065,
                            SenderId = 11,
                            TransactionAmount = 2785,
                            TransactionDate = new DateTime(2024, 8, 16, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7547),
                            TransactionDescription = "Payment from 770065 to 770065"
                        },
                        new
                        {
                            TransactionId = 121,
                            ReceiverAccountNo = 475083,
                            ReceiverId = 12,
                            SenderAccountNo = 475083,
                            SenderId = 12,
                            TransactionAmount = 4341,
                            TransactionDate = new DateTime(2024, 7, 25, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7557),
                            TransactionDescription = "Payment from 475083 to 475083"
                        },
                        new
                        {
                            TransactionId = 122,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 475083,
                            SenderId = 12,
                            TransactionAmount = 624,
                            TransactionDate = new DateTime(2024, 7, 16, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7559),
                            TransactionDescription = "Payment from 475083 to 770065"
                        },
                        new
                        {
                            TransactionId = 123,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 475083,
                            SenderId = 12,
                            TransactionAmount = 3160,
                            TransactionDate = new DateTime(2024, 7, 14, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7561),
                            TransactionDescription = "Payment from 475083 to 770065"
                        },
                        new
                        {
                            TransactionId = 124,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 475083,
                            SenderId = 12,
                            TransactionAmount = 455,
                            TransactionDate = new DateTime(2024, 7, 14, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7562),
                            TransactionDescription = "Payment from 475083 to 770065"
                        },
                        new
                        {
                            TransactionId = 125,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 475083,
                            SenderId = 12,
                            TransactionAmount = 3689,
                            TransactionDate = new DateTime(2024, 8, 8, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7565),
                            TransactionDescription = "Payment from 475083 to 770065"
                        },
                        new
                        {
                            TransactionId = 131,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 880816,
                            SenderId = 13,
                            TransactionAmount = 4047,
                            TransactionDate = new DateTime(2024, 9, 4, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7573),
                            TransactionDescription = "Payment from 880816 to 880816"
                        },
                        new
                        {
                            TransactionId = 132,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 880816,
                            SenderId = 13,
                            TransactionAmount = 1059,
                            TransactionDate = new DateTime(2024, 9, 1, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7574),
                            TransactionDescription = "Payment from 880816 to 880816"
                        },
                        new
                        {
                            TransactionId = 133,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 880816,
                            SenderId = 13,
                            TransactionAmount = 4273,
                            TransactionDate = new DateTime(2024, 9, 18, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7576),
                            TransactionDescription = "Payment from 880816 to 880816"
                        },
                        new
                        {
                            TransactionId = 134,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 880816,
                            SenderId = 13,
                            TransactionAmount = 3314,
                            TransactionDate = new DateTime(2024, 8, 24, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7579),
                            TransactionDescription = "Payment from 880816 to 880816"
                        },
                        new
                        {
                            TransactionId = 135,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 880816,
                            SenderId = 13,
                            TransactionAmount = 3492,
                            TransactionDate = new DateTime(2024, 10, 10, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7581),
                            TransactionDescription = "Payment from 880816 to 770065"
                        },
                        new
                        {
                            TransactionId = 211,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 309277,
                            SenderId = 21,
                            TransactionAmount = 1297,
                            TransactionDate = new DateTime(2024, 7, 9, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7590),
                            TransactionDescription = "Payment from 309277 to 880816"
                        },
                        new
                        {
                            TransactionId = 212,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 309277,
                            SenderId = 21,
                            TransactionAmount = 1096,
                            TransactionDate = new DateTime(2024, 9, 11, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7592),
                            TransactionDescription = "Payment from 309277 to 880816"
                        },
                        new
                        {
                            TransactionId = 213,
                            ReceiverAccountNo = 309277,
                            ReceiverId = 21,
                            SenderAccountNo = 309277,
                            SenderId = 21,
                            TransactionAmount = 3193,
                            TransactionDate = new DateTime(2024, 9, 14, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7595),
                            TransactionDescription = "Payment from 309277 to 309277"
                        },
                        new
                        {
                            TransactionId = 214,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 309277,
                            SenderId = 21,
                            TransactionAmount = 4031,
                            TransactionDate = new DateTime(2024, 7, 26, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7596),
                            TransactionDescription = "Payment from 309277 to 770065"
                        },
                        new
                        {
                            TransactionId = 215,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 309277,
                            SenderId = 21,
                            TransactionAmount = 2028,
                            TransactionDate = new DateTime(2024, 9, 23, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7599),
                            TransactionDescription = "Payment from 309277 to 770065"
                        },
                        new
                        {
                            TransactionId = 221,
                            ReceiverAccountNo = 309277,
                            ReceiverId = 21,
                            SenderAccountNo = 751640,
                            SenderId = 22,
                            TransactionAmount = 1412,
                            TransactionDate = new DateTime(2024, 7, 19, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7604),
                            TransactionDescription = "Payment from 751640 to 309277"
                        },
                        new
                        {
                            TransactionId = 222,
                            ReceiverAccountNo = 751640,
                            ReceiverId = 22,
                            SenderAccountNo = 751640,
                            SenderId = 22,
                            TransactionAmount = 4256,
                            TransactionDate = new DateTime(2024, 8, 28, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7605),
                            TransactionDescription = "Payment from 751640 to 751640"
                        },
                        new
                        {
                            TransactionId = 223,
                            ReceiverAccountNo = 751640,
                            ReceiverId = 22,
                            SenderAccountNo = 751640,
                            SenderId = 22,
                            TransactionAmount = 3746,
                            TransactionDate = new DateTime(2024, 9, 19, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7607),
                            TransactionDescription = "Payment from 751640 to 751640"
                        },
                        new
                        {
                            TransactionId = 224,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 751640,
                            SenderId = 22,
                            TransactionAmount = 576,
                            TransactionDate = new DateTime(2024, 8, 1, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7609),
                            TransactionDescription = "Payment from 751640 to 770065"
                        },
                        new
                        {
                            TransactionId = 225,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 751640,
                            SenderId = 22,
                            TransactionAmount = 4535,
                            TransactionDate = new DateTime(2024, 8, 1, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7611),
                            TransactionDescription = "Payment from 751640 to 880816"
                        },
                        new
                        {
                            TransactionId = 231,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 733924,
                            SenderId = 23,
                            TransactionAmount = 759,
                            TransactionDate = new DateTime(2024, 8, 28, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7615),
                            TransactionDescription = "Payment from 733924 to 880816"
                        },
                        new
                        {
                            TransactionId = 232,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 733924,
                            SenderId = 23,
                            TransactionAmount = 3205,
                            TransactionDate = new DateTime(2024, 8, 29, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7617),
                            TransactionDescription = "Payment from 733924 to 880816"
                        },
                        new
                        {
                            TransactionId = 233,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 733924,
                            SenderId = 23,
                            TransactionAmount = 1445,
                            TransactionDate = new DateTime(2024, 7, 29, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7618),
                            TransactionDescription = "Payment from 733924 to 770065"
                        },
                        new
                        {
                            TransactionId = 234,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 733924,
                            SenderId = 23,
                            TransactionAmount = 588,
                            TransactionDate = new DateTime(2024, 7, 30, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7620),
                            TransactionDescription = "Payment from 733924 to 880816"
                        },
                        new
                        {
                            TransactionId = 235,
                            ReceiverAccountNo = 733924,
                            ReceiverId = 23,
                            SenderAccountNo = 733924,
                            SenderId = 23,
                            TransactionAmount = 4010,
                            TransactionDate = new DateTime(2024, 9, 7, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7622),
                            TransactionDescription = "Payment from 733924 to 733924"
                        },
                        new
                        {
                            TransactionId = 311,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 897546,
                            SenderId = 31,
                            TransactionAmount = 1978,
                            TransactionDate = new DateTime(2024, 8, 2, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7630),
                            TransactionDescription = "Payment from 897546 to 770065"
                        },
                        new
                        {
                            TransactionId = 312,
                            ReceiverAccountNo = 475083,
                            ReceiverId = 12,
                            SenderAccountNo = 897546,
                            SenderId = 31,
                            TransactionAmount = 2960,
                            TransactionDate = new DateTime(2024, 8, 8, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7631),
                            TransactionDescription = "Payment from 897546 to 475083"
                        },
                        new
                        {
                            TransactionId = 313,
                            ReceiverAccountNo = 475083,
                            ReceiverId = 12,
                            SenderAccountNo = 897546,
                            SenderId = 31,
                            TransactionAmount = 159,
                            TransactionDate = new DateTime(2024, 9, 25, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7633),
                            TransactionDescription = "Payment from 897546 to 475083"
                        },
                        new
                        {
                            TransactionId = 314,
                            ReceiverAccountNo = 309277,
                            ReceiverId = 21,
                            SenderAccountNo = 897546,
                            SenderId = 31,
                            TransactionAmount = 1402,
                            TransactionDate = new DateTime(2024, 8, 28, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7635),
                            TransactionDescription = "Payment from 897546 to 309277"
                        },
                        new
                        {
                            TransactionId = 315,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 897546,
                            SenderId = 31,
                            TransactionAmount = 2019,
                            TransactionDate = new DateTime(2024, 9, 7, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7637),
                            TransactionDescription = "Payment from 897546 to 880816"
                        },
                        new
                        {
                            TransactionId = 321,
                            ReceiverAccountNo = 897546,
                            ReceiverId = 31,
                            SenderAccountNo = 338677,
                            SenderId = 32,
                            TransactionAmount = 64,
                            TransactionDate = new DateTime(2024, 7, 13, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7680),
                            TransactionDescription = "Payment from 338677 to 897546"
                        },
                        new
                        {
                            TransactionId = 322,
                            ReceiverAccountNo = 309277,
                            ReceiverId = 21,
                            SenderAccountNo = 338677,
                            SenderId = 32,
                            TransactionAmount = 2545,
                            TransactionDate = new DateTime(2024, 7, 26, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7682),
                            TransactionDescription = "Payment from 338677 to 309277"
                        },
                        new
                        {
                            TransactionId = 323,
                            ReceiverAccountNo = 309277,
                            ReceiverId = 21,
                            SenderAccountNo = 338677,
                            SenderId = 32,
                            TransactionAmount = 4594,
                            TransactionDate = new DateTime(2024, 9, 8, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7684),
                            TransactionDescription = "Payment from 338677 to 309277"
                        },
                        new
                        {
                            TransactionId = 324,
                            ReceiverAccountNo = 751640,
                            ReceiverId = 22,
                            SenderAccountNo = 338677,
                            SenderId = 32,
                            TransactionAmount = 533,
                            TransactionDate = new DateTime(2024, 10, 9, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7686),
                            TransactionDescription = "Payment from 338677 to 751640"
                        },
                        new
                        {
                            TransactionId = 325,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 338677,
                            SenderId = 32,
                            TransactionAmount = 703,
                            TransactionDate = new DateTime(2024, 8, 22, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7687),
                            TransactionDescription = "Payment from 338677 to 770065"
                        },
                        new
                        {
                            TransactionId = 331,
                            ReceiverAccountNo = 733924,
                            ReceiverId = 23,
                            SenderAccountNo = 354018,
                            SenderId = 33,
                            TransactionAmount = 2223,
                            TransactionDate = new DateTime(2024, 9, 9, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7692),
                            TransactionDescription = "Payment from 354018 to 733924"
                        },
                        new
                        {
                            TransactionId = 332,
                            ReceiverAccountNo = 733924,
                            ReceiverId = 23,
                            SenderAccountNo = 354018,
                            SenderId = 33,
                            TransactionAmount = 3284,
                            TransactionDate = new DateTime(2024, 9, 1, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7694),
                            TransactionDescription = "Payment from 354018 to 733924"
                        },
                        new
                        {
                            TransactionId = 333,
                            ReceiverAccountNo = 309277,
                            ReceiverId = 21,
                            SenderAccountNo = 354018,
                            SenderId = 33,
                            TransactionAmount = 4397,
                            TransactionDate = new DateTime(2024, 7, 14, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7696),
                            TransactionDescription = "Payment from 354018 to 309277"
                        },
                        new
                        {
                            TransactionId = 334,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 354018,
                            SenderId = 33,
                            TransactionAmount = 2101,
                            TransactionDate = new DateTime(2024, 8, 2, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7698),
                            TransactionDescription = "Payment from 354018 to 770065"
                        },
                        new
                        {
                            TransactionId = 335,
                            ReceiverAccountNo = 733924,
                            ReceiverId = 23,
                            SenderAccountNo = 354018,
                            SenderId = 33,
                            TransactionAmount = 1405,
                            TransactionDate = new DateTime(2024, 7, 5, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7700),
                            TransactionDescription = "Payment from 354018 to 733924"
                        },
                        new
                        {
                            TransactionId = 411,
                            ReceiverAccountNo = 733924,
                            ReceiverId = 23,
                            SenderAccountNo = 837691,
                            SenderId = 41,
                            TransactionAmount = 4746,
                            TransactionDate = new DateTime(2024, 7, 28, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7708),
                            TransactionDescription = "Payment from 837691 to 733924"
                        },
                        new
                        {
                            TransactionId = 412,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 837691,
                            SenderId = 41,
                            TransactionAmount = 1681,
                            TransactionDate = new DateTime(2024, 10, 9, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7709),
                            TransactionDescription = "Payment from 837691 to 770065"
                        },
                        new
                        {
                            TransactionId = 413,
                            ReceiverAccountNo = 309277,
                            ReceiverId = 21,
                            SenderAccountNo = 837691,
                            SenderId = 41,
                            TransactionAmount = 679,
                            TransactionDate = new DateTime(2024, 8, 7, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7711),
                            TransactionDescription = "Payment from 837691 to 309277"
                        },
                        new
                        {
                            TransactionId = 414,
                            ReceiverAccountNo = 354018,
                            ReceiverId = 33,
                            SenderAccountNo = 837691,
                            SenderId = 41,
                            TransactionAmount = 1275,
                            TransactionDate = new DateTime(2024, 9, 16, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7713),
                            TransactionDescription = "Payment from 837691 to 354018"
                        },
                        new
                        {
                            TransactionId = 415,
                            ReceiverAccountNo = 338677,
                            ReceiverId = 32,
                            SenderAccountNo = 837691,
                            SenderId = 41,
                            TransactionAmount = 3390,
                            TransactionDate = new DateTime(2024, 9, 25, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7715),
                            TransactionDescription = "Payment from 837691 to 338677"
                        },
                        new
                        {
                            TransactionId = 421,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 210342,
                            SenderId = 42,
                            TransactionAmount = 3245,
                            TransactionDate = new DateTime(2024, 9, 16, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7720),
                            TransactionDescription = "Payment from 210342 to 880816"
                        },
                        new
                        {
                            TransactionId = 422,
                            ReceiverAccountNo = 837691,
                            ReceiverId = 41,
                            SenderAccountNo = 210342,
                            SenderId = 42,
                            TransactionAmount = 1168,
                            TransactionDate = new DateTime(2024, 8, 16, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7721),
                            TransactionDescription = "Payment from 210342 to 837691"
                        },
                        new
                        {
                            TransactionId = 423,
                            ReceiverAccountNo = 354018,
                            ReceiverId = 33,
                            SenderAccountNo = 210342,
                            SenderId = 42,
                            TransactionAmount = 807,
                            TransactionDate = new DateTime(2024, 9, 29, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7723),
                            TransactionDescription = "Payment from 210342 to 354018"
                        },
                        new
                        {
                            TransactionId = 424,
                            ReceiverAccountNo = 338677,
                            ReceiverId = 32,
                            SenderAccountNo = 210342,
                            SenderId = 42,
                            TransactionAmount = 4234,
                            TransactionDate = new DateTime(2024, 7, 27, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7725),
                            TransactionDescription = "Payment from 210342 to 338677"
                        },
                        new
                        {
                            TransactionId = 425,
                            ReceiverAccountNo = 354018,
                            ReceiverId = 33,
                            SenderAccountNo = 210342,
                            SenderId = 42,
                            TransactionAmount = 3631,
                            TransactionDate = new DateTime(2024, 8, 7, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7727),
                            TransactionDescription = "Payment from 210342 to 354018"
                        },
                        new
                        {
                            TransactionId = 431,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 348418,
                            SenderId = 43,
                            TransactionAmount = 2219,
                            TransactionDate = new DateTime(2024, 7, 29, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7732),
                            TransactionDescription = "Payment from 348418 to 770065"
                        },
                        new
                        {
                            TransactionId = 432,
                            ReceiverAccountNo = 733924,
                            ReceiverId = 23,
                            SenderAccountNo = 348418,
                            SenderId = 43,
                            TransactionAmount = 3529,
                            TransactionDate = new DateTime(2024, 8, 8, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7734),
                            TransactionDescription = "Payment from 348418 to 733924"
                        },
                        new
                        {
                            TransactionId = 433,
                            ReceiverAccountNo = 897546,
                            ReceiverId = 31,
                            SenderAccountNo = 348418,
                            SenderId = 43,
                            TransactionAmount = 2838,
                            TransactionDate = new DateTime(2024, 9, 14, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7735),
                            TransactionDescription = "Payment from 348418 to 897546"
                        },
                        new
                        {
                            TransactionId = 434,
                            ReceiverAccountNo = 897546,
                            ReceiverId = 31,
                            SenderAccountNo = 348418,
                            SenderId = 43,
                            TransactionAmount = 1913,
                            TransactionDate = new DateTime(2024, 8, 8, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7737),
                            TransactionDescription = "Payment from 348418 to 897546"
                        },
                        new
                        {
                            TransactionId = 435,
                            ReceiverAccountNo = 733924,
                            ReceiverId = 23,
                            SenderAccountNo = 348418,
                            SenderId = 43,
                            TransactionAmount = 1143,
                            TransactionDate = new DateTime(2024, 8, 18, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7739),
                            TransactionDescription = "Payment from 348418 to 733924"
                        },
                        new
                        {
                            TransactionId = 511,
                            ReceiverAccountNo = 354018,
                            ReceiverId = 33,
                            SenderAccountNo = 470073,
                            SenderId = 51,
                            TransactionAmount = 1977,
                            TransactionDate = new DateTime(2024, 7, 23, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7748),
                            TransactionDescription = "Payment from 470073 to 354018"
                        },
                        new
                        {
                            TransactionId = 512,
                            ReceiverAccountNo = 470073,
                            ReceiverId = 51,
                            SenderAccountNo = 470073,
                            SenderId = 51,
                            TransactionAmount = 3188,
                            TransactionDate = new DateTime(2024, 8, 21, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7750),
                            TransactionDescription = "Payment from 470073 to 470073"
                        },
                        new
                        {
                            TransactionId = 513,
                            ReceiverAccountNo = 733924,
                            ReceiverId = 23,
                            SenderAccountNo = 470073,
                            SenderId = 51,
                            TransactionAmount = 1303,
                            TransactionDate = new DateTime(2024, 8, 28, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7751),
                            TransactionDescription = "Payment from 470073 to 733924"
                        },
                        new
                        {
                            TransactionId = 514,
                            ReceiverAccountNo = 309277,
                            ReceiverId = 21,
                            SenderAccountNo = 470073,
                            SenderId = 51,
                            TransactionAmount = 4902,
                            TransactionDate = new DateTime(2024, 7, 12, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7753),
                            TransactionDescription = "Payment from 470073 to 309277"
                        },
                        new
                        {
                            TransactionId = 515,
                            ReceiverAccountNo = 733924,
                            ReceiverId = 23,
                            SenderAccountNo = 470073,
                            SenderId = 51,
                            TransactionAmount = 448,
                            TransactionDate = new DateTime(2024, 9, 5, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7755),
                            TransactionDescription = "Payment from 470073 to 733924"
                        },
                        new
                        {
                            TransactionId = 521,
                            ReceiverAccountNo = 475083,
                            ReceiverId = 12,
                            SenderAccountNo = 596000,
                            SenderId = 52,
                            TransactionAmount = 2821,
                            TransactionDate = new DateTime(2024, 8, 8, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7761),
                            TransactionDescription = "Payment from 596000 to 475083"
                        },
                        new
                        {
                            TransactionId = 522,
                            ReceiverAccountNo = 470073,
                            ReceiverId = 51,
                            SenderAccountNo = 596000,
                            SenderId = 52,
                            TransactionAmount = 4003,
                            TransactionDate = new DateTime(2024, 8, 13, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7763),
                            TransactionDescription = "Payment from 596000 to 470073"
                        },
                        new
                        {
                            TransactionId = 523,
                            ReceiverAccountNo = 470073,
                            ReceiverId = 51,
                            SenderAccountNo = 596000,
                            SenderId = 52,
                            TransactionAmount = 707,
                            TransactionDate = new DateTime(2024, 7, 25, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7804),
                            TransactionDescription = "Payment from 596000 to 470073"
                        },
                        new
                        {
                            TransactionId = 524,
                            ReceiverAccountNo = 751640,
                            ReceiverId = 22,
                            SenderAccountNo = 596000,
                            SenderId = 52,
                            TransactionAmount = 57,
                            TransactionDate = new DateTime(2024, 7, 31, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7806),
                            TransactionDescription = "Payment from 596000 to 751640"
                        },
                        new
                        {
                            TransactionId = 525,
                            ReceiverAccountNo = 837691,
                            ReceiverId = 41,
                            SenderAccountNo = 596000,
                            SenderId = 52,
                            TransactionAmount = 3586,
                            TransactionDate = new DateTime(2024, 7, 29, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7808),
                            TransactionDescription = "Payment from 596000 to 837691"
                        },
                        new
                        {
                            TransactionId = 531,
                            ReceiverAccountNo = 470073,
                            ReceiverId = 51,
                            SenderAccountNo = 949319,
                            SenderId = 53,
                            TransactionAmount = 4319,
                            TransactionDate = new DateTime(2024, 7, 7, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7813),
                            TransactionDescription = "Payment from 949319 to 470073"
                        },
                        new
                        {
                            TransactionId = 532,
                            ReceiverAccountNo = 354018,
                            ReceiverId = 33,
                            SenderAccountNo = 949319,
                            SenderId = 53,
                            TransactionAmount = 1825,
                            TransactionDate = new DateTime(2024, 9, 8, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7815),
                            TransactionDescription = "Payment from 949319 to 354018"
                        },
                        new
                        {
                            TransactionId = 533,
                            ReceiverAccountNo = 733924,
                            ReceiverId = 23,
                            SenderAccountNo = 949319,
                            SenderId = 53,
                            TransactionAmount = 4933,
                            TransactionDate = new DateTime(2024, 7, 29, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7817),
                            TransactionDescription = "Payment from 949319 to 733924"
                        },
                        new
                        {
                            TransactionId = 534,
                            ReceiverAccountNo = 210342,
                            ReceiverId = 42,
                            SenderAccountNo = 949319,
                            SenderId = 53,
                            TransactionAmount = 595,
                            TransactionDate = new DateTime(2024, 8, 11, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7819),
                            TransactionDescription = "Payment from 949319 to 210342"
                        },
                        new
                        {
                            TransactionId = 535,
                            ReceiverAccountNo = 837691,
                            ReceiverId = 41,
                            SenderAccountNo = 949319,
                            SenderId = 53,
                            TransactionAmount = 2396,
                            TransactionDate = new DateTime(2024, 8, 25, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7821),
                            TransactionDescription = "Payment from 949319 to 837691"
                        },
                        new
                        {
                            TransactionId = 611,
                            ReceiverAccountNo = 470073,
                            ReceiverId = 51,
                            SenderAccountNo = 571118,
                            SenderId = 61,
                            TransactionAmount = 156,
                            TransactionDate = new DateTime(2024, 8, 18, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7829),
                            TransactionDescription = "Payment from 571118 to 470073"
                        },
                        new
                        {
                            TransactionId = 612,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 571118,
                            SenderId = 61,
                            TransactionAmount = 1154,
                            TransactionDate = new DateTime(2024, 7, 30, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7831),
                            TransactionDescription = "Payment from 571118 to 880816"
                        },
                        new
                        {
                            TransactionId = 613,
                            ReceiverAccountNo = 348418,
                            ReceiverId = 43,
                            SenderAccountNo = 571118,
                            SenderId = 61,
                            TransactionAmount = 4319,
                            TransactionDate = new DateTime(2024, 8, 22, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7833),
                            TransactionDescription = "Payment from 571118 to 348418"
                        },
                        new
                        {
                            TransactionId = 614,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 571118,
                            SenderId = 61,
                            TransactionAmount = 2677,
                            TransactionDate = new DateTime(2024, 9, 17, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7835),
                            TransactionDescription = "Payment from 571118 to 770065"
                        },
                        new
                        {
                            TransactionId = 615,
                            ReceiverAccountNo = 880816,
                            ReceiverId = 13,
                            SenderAccountNo = 571118,
                            SenderId = 61,
                            TransactionAmount = 1721,
                            TransactionDate = new DateTime(2024, 9, 16, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7837),
                            TransactionDescription = "Payment from 571118 to 880816"
                        },
                        new
                        {
                            TransactionId = 621,
                            ReceiverAccountNo = 837691,
                            ReceiverId = 41,
                            SenderAccountNo = 339286,
                            SenderId = 62,
                            TransactionAmount = 1901,
                            TransactionDate = new DateTime(2024, 9, 7, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7843),
                            TransactionDescription = "Payment from 339286 to 837691"
                        },
                        new
                        {
                            TransactionId = 622,
                            ReceiverAccountNo = 470073,
                            ReceiverId = 51,
                            SenderAccountNo = 339286,
                            SenderId = 62,
                            TransactionAmount = 2767,
                            TransactionDate = new DateTime(2024, 8, 19, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7845),
                            TransactionDescription = "Payment from 339286 to 470073"
                        },
                        new
                        {
                            TransactionId = 623,
                            ReceiverAccountNo = 770065,
                            ReceiverId = 11,
                            SenderAccountNo = 339286,
                            SenderId = 62,
                            TransactionAmount = 4954,
                            TransactionDate = new DateTime(2024, 9, 25, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7847),
                            TransactionDescription = "Payment from 339286 to 770065"
                        },
                        new
                        {
                            TransactionId = 624,
                            ReceiverAccountNo = 309277,
                            ReceiverId = 21,
                            SenderAccountNo = 339286,
                            SenderId = 62,
                            TransactionAmount = 583,
                            TransactionDate = new DateTime(2024, 10, 10, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7849),
                            TransactionDescription = "Payment from 339286 to 309277"
                        },
                        new
                        {
                            TransactionId = 625,
                            ReceiverAccountNo = 338677,
                            ReceiverId = 32,
                            SenderAccountNo = 339286,
                            SenderId = 62,
                            TransactionAmount = 360,
                            TransactionDate = new DateTime(2024, 7, 23, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7851),
                            TransactionDescription = "Payment from 339286 to 338677"
                        },
                        new
                        {
                            TransactionId = 631,
                            ReceiverAccountNo = 210342,
                            ReceiverId = 42,
                            SenderAccountNo = 786190,
                            SenderId = 63,
                            TransactionAmount = 2381,
                            TransactionDate = new DateTime(2024, 7, 7, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7856),
                            TransactionDescription = "Payment from 786190 to 210342"
                        },
                        new
                        {
                            TransactionId = 632,
                            ReceiverAccountNo = 309277,
                            ReceiverId = 21,
                            SenderAccountNo = 786190,
                            SenderId = 63,
                            TransactionAmount = 1628,
                            TransactionDate = new DateTime(2024, 7, 23, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7858),
                            TransactionDescription = "Payment from 786190 to 309277"
                        },
                        new
                        {
                            TransactionId = 633,
                            ReceiverAccountNo = 751640,
                            ReceiverId = 22,
                            SenderAccountNo = 786190,
                            SenderId = 63,
                            TransactionAmount = 929,
                            TransactionDate = new DateTime(2024, 7, 21, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7860),
                            TransactionDescription = "Payment from 786190 to 751640"
                        },
                        new
                        {
                            TransactionId = 634,
                            ReceiverAccountNo = 786190,
                            ReceiverId = 63,
                            SenderAccountNo = 786190,
                            SenderId = 63,
                            TransactionAmount = 4472,
                            TransactionDate = new DateTime(2024, 8, 21, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7862),
                            TransactionDescription = "Payment from 786190 to 786190"
                        },
                        new
                        {
                            TransactionId = 635,
                            ReceiverAccountNo = 571118,
                            ReceiverId = 61,
                            SenderAccountNo = 786190,
                            SenderId = 63,
                            TransactionAmount = 3034,
                            TransactionDate = new DateTime(2024, 7, 23, 21, 3, 5, 127, DateTimeKind.Local).AddTicks(7864),
                            TransactionDescription = "Payment from 786190 to 571118"
                        });
                });

            modelBuilder.Entity("BankDataModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNo")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProfilePicdBytes")
                        .HasColumnType("BLOB");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "jane.miller64@example.com",
                            Name = "Jane Miller",
                            Password = "123",
                            PhoneNo = 253275709
                        },
                        new
                        {
                            UserId = 2,
                            Email = "john.brown9@example.com",
                            Name = "John Brown",
                            Password = "123",
                            PhoneNo = 537849027
                        },
                        new
                        {
                            UserId = 3,
                            Email = "jane.jones45@example.com",
                            Name = "Jane Jones",
                            Password = "123",
                            PhoneNo = 273990287
                        },
                        new
                        {
                            UserId = 4,
                            Email = "michael.smith50@example.com",
                            Name = "Michael Smith",
                            Password = "123",
                            PhoneNo = 493115021
                        },
                        new
                        {
                            UserId = 5,
                            Email = "john.brown72@example.com",
                            Name = "John Brown",
                            Password = "123",
                            PhoneNo = 149130245
                        },
                        new
                        {
                            UserId = 6,
                            Email = "john.miller89@example.com",
                            Name = "John Miller",
                            Password = "123",
                            PhoneNo = 290765618
                        });
                });

            modelBuilder.Entity("BankDataModels.Account", b =>
                {
                    b.HasOne("BankDataModels.User", "AccountHolder")
                        .WithMany("AccountList")
                        .HasForeignKey("AccountHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountHolder");
                });

            modelBuilder.Entity("BankDataModels.Transaction", b =>
                {
                    b.HasOne("BankDataModels.Account", "SenderAccount")
                        .WithMany("TransactionList")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SenderAccount");
                });

            modelBuilder.Entity("BankDataModels.Account", b =>
                {
                    b.Navigation("TransactionList");
                });

            modelBuilder.Entity("BankDataModels.User", b =>
                {
                    b.Navigation("AccountList");
                });
#pragma warning restore 612, 618
        }
    }
}
